name: clingoJupyter
channels:
  - conda-forge
  - defaults
  - potassco/label/dev
  - potassco
dependencies:
  - python=3.9
  - ipython=7.19
  - jupyter_contrib_nbextensions
  - clingo
  - clorm
  - pandas
  - matplotlib


