#!/bin/bash
IPYLOC=`ipython locate profile`
echo 'alias_magic clingo script -p "clingo --no-raise-error"' >> $IPYLOC/startup/config.ipy
jupyter nbextension enable collapsible_headings/main --user
jupyter nbextension enable toc2/main --user